apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./sre.yaml
    - ./sreB.yaml
    - ./sreC.yaml
    - ./sreD.yaml
    - ./devops.yaml
    - ./CNB.yaml
