apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: SRE-A
  description: It is the team of SREs
  links:
    - url: https://www.cnb.com/
      title: WEBSITE
      icon: website
    - url: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/domains/artists-domain.yaml
      title: GITHUB Repo
      icon: github
    - url: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/domains/artists-domain.yaml
      title: Documentation
      icon: doc
spec:
  type: team
  profile:
    email: team-a@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: breanna.davison
spec:
  profile:
    displayName: Janelle Dawe (Business Owner)
    email: breanna-davison@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [SRE-A]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [SRE-A]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning
spec:
  profile:
    displayName: Nigel Manning (Technical Owner)
    email: nigel-manning@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight&backgroundColor=transparent
  memberOf: [SRE-A]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: navdeep.singh
spec:
  profile:
    displayName: navdeep-12
    email: navdeep.singh@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight&backgroundColor=transparent
  memberOf: [SRE-A]
---
