apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CNBID
  description: CNBID Application
  annotations:
    backstage.io/techdocs-ref: 'url:https://www.cnb.com/'
    backstage.io/source-location: 'url:https://github.com/swagger-api/swagger-petstore'
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore
      title: Website
      icon: Website
    - url: https://github.com/swagger-api/swagger-petstore
      title: Cloud
      icon: cloud
    - url: https://github.com/swagger-api/swagger-petstore
      title: Group
      icon: group
    - url: https://github.com/swagger-api/swagger-petstore
      title: User
      icon: user
spec:
  type: Website
  lifecycle: production
  owner: SRE-A
  system: LENDING
  dependsOn: ['resource:dynatrace', 'resource:elk']
  providesApis:
    - streetlights
    - hello-world
